base_model_id: TinyLlama/TinyLlama-1.1B-Chat-v1.0
model_name: tinyllama-guanaco-jp-v1
output_base_dir: output
dataset_id: fujiki/guanaco_jp
dataset_input_field_name: instruction
dataset_input_context_hint: 以下のcontextに基づいて、質問に答えてください
dataset_input_context_field_name: input
dataset_output_field_name: output
dataset_train_split_seed: 42
dataset_train_split_test_size: 0.2
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
train_per_device_train_batch_size: 8
train_gradient_accumulation_steps: 2
train_num_train_epochs: 4
train_max_steps: 200
train_fp16: True
inference_max_new_tokens: 32
evaluation_prompts_with_context:
  - 
    prompt: "How many heads of the departments are older than 56 ?"
    context: "CREATE TABLE head (age INTEGER)"
