base_model_id: TinyLlama/TinyLlama-1.1B-Chat-v1.0
model_name: tinyllama-colorist-v1
output_base_dir: output
dataset_id: burkelibbey/colors
dataset_input_field_name: description
dataset_output_field_name: color
dataset_train_split_seed: 42
dataset_train_split_test_size: 0.2
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
train_per_device_train_batch_size: 8
train_gradient_accumulation_steps: 2
train_num_train_epochs: 4
train_max_steps: 200
train_fp16: True
inference_max_new_tokens: 16
evaluation_prompts:
  - "Pure Black: A shade that completely absorbs light and does not reflect any colors. It is the darkest possible shade."
  - "Deep orange-brown: This color is a rich blend of orange and brown, similar to the hue of an autumn leaves or old-fashioned rust. It's vivid but also carries a decent amount of earthy depth."
  - "pure brown color"
  - "light orange color"
