base_model_id: TinyLlama/TinyLlama-1.1B-Chat-v1.0
model_name: tinyllama-hh-rlhf-49k-ja-v1
output_base_dir: output
dataset_id: hotchpotch/JQaRA
dataset_input_field_name: question
dataset_input_context_hint: 以下のcontextに基づいて、質問に答えてください
dataset_input_context_field_name: text
dataset_output_field_name: answer
dataset_train_split_seed: 42
dataset_train_split_test_size: 0.4
lora_r: 8
lora_alpha: 16
lora_dropout: 0.05
train_per_device_train_batch_size: 8
train_gradient_accumulation_steps: 2
train_num_train_epochs: 2
train_max_steps: 200
train_fp16: True
inference_max_new_tokens: 64
evaluation_prompts_with_context:
  -
    prompt: "雑誌『週刊文春』が著名人のスキャンダルをスクープすることを、兵器に例えた表現で何というでしょう?"
    context: "2016年の初めころから、週刊文春のスクープ記事により政治家・著名人が辞任や活動停止に追い込まれるケースが増えたことから『文春砲』と恐れられるようになった。2004年に鈴木が編集長に就任して以来、読売新聞および読売新聞グループ本社会長・渡邉恒雄を徹底的に批判しているが、読売から損害賠償請求や謝罪広告を求める訴訟を起こされ、その多くで敗訴している。他の大手出版社と異なり、ジャニーズ事務所が影響力をほとんど持たないため、1999年から2000年にかけて社長・ジャニー喜多川の児童(ジャニーズJr.の研修生たち)への性的虐待疑惑を報道した。ニューヨーク・タイムズやオブザーバーなどの国外メディアも後追いし、国会でも取り上げられるなど内外に波紋を広げた。"